# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "FloorPlay" do

pod 'AFNetworking', '2.2.1'
pod 'AGGeometryKit', '1.0.2'
pod 'MWPhotoBrowser', '1.4.0'

end

target "FloorPlayTests" do

end

